# this file is for me deploying the bot myself. if you are deploying the bot to heroku, simply ignore this
name: Deploying bot
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
        curl --header 'Authorization: token ${{ secrets.ENV_TOKEN }}' --header 'Accept: application/vnd.github.v3.raw' --remote-name --location ${{ secrets.ENV_URL }}
    - name: Kill running process
      run: pm2 kill
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependency
      run: npm i
    - name: Start app
      run: pm2 start ecosystem.config.js --update-env
