# this file is for me deploying the bot myself. if you are deploying the bot to heroku, simply ignore this
name: Deploying bot
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Kill process
      run: pm2 kill
    - name: Install dependency
      run: npm i --allow-root --unsafe-perm=true
    - name: Create .env file
      run: |
        curl --header 'Authorization: token ${{ secrets.ENV_TOKEN }}' --header 'Accept: application/vnd.github.v3.raw' --remote-name --location ${{ secrets.ENV_URL }}
    - name: Start app
      run: pm2 start main.js --name "Sefy"
