# this file is for me deploying the bot myself. if you are deploying the bot to heroku, simply ignore this
name: Deploying bot
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
        curl --header 'Authorization: token ${{ secrets.ENV_TOKEN }}' --header 'Accept: application/vnd.github.v3.raw' --remote-name --location ${{ secrets.ENV_URL }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependency
      run: npm i
    - name: Kill any current bot process
      run: npm i
  launch:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: SSH and deploy bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_SSH_HOST }}
        username: ${{ secrets.EC2_SSH_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          cd ${{ secrets.SSH_PATH }}
          pm2 restart ecosystem.config.js --update-env


